"""
PDF Report Generator module.

Generates a publication-ready PDF Data Quality Audit Report containing:
1. Executive Summary & Quality Scores
2. Issues Found (Baseline vs. AI Scanner)
3. Clinical Impact Analysis
4. Recommended Actions
"""

import os
import tempfile
from typing import Dict, Any, List

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable


def generate_pdf_report(
    scores: Dict[str, Any],
    issues: List[Dict[str, Any]],
    cohort_summary: Dict[str, Any] = None,
    output_path: str = None
) -> str:
    """
    Generates a PDF audit report and saves it to output_path.
    If output_path is None, saves to a temporary file.
    Returns the file path of the generated PDF.
    """
    if output_path is None:
        fd, output_path = tempfile.mkstemp(suffix="_mimic_quality_report.pdf")
        os.close(fd)

    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#0f172a')
    )
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#0284c7')
    )
    heading2_style = ParagraphStyle(
        'Heading2Custom',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#1e293b'),
        spaceBefore=12,
        spaceAfter=6
    )
    body_style = ParagraphStyle(
        'BodyCustom',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=12,
        textColor=colors.HexColor('#334155')
    )
    table_header_style = ParagraphStyle(
        'TableHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=11,
        textColor=colors.white
    )

    story = []

    # Title & Header
    story.append(Paragraph("MIMIC-IV Data Quality & Clinical Audit Report", title_style))
    story.append(Paragraph("Sofstica Hackathon 2026 · AI for Smarter Patient Care · Track 2 Prototype", subtitle_style))
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#0284c7'), spaceAfter=15))

    # Executive Summary & Quality Scores Table
    story.append(Paragraph("1. Executive Summary & Dataset Quality Scores", heading2_style))
    story.append(Paragraph(
        "This audit report summarizes data quality findings generated by comparing hardcoded "
        "baseline rules against the AI/ML statistical quality scanner on MIMIC-IV clinical tables.",
        body_style
    ))
    story.append(Spacer(1, 8))

    score_data = [
        [Paragraph("Metric Score Category", table_header_style), Paragraph("Score (0 - 100)", table_header_style), Paragraph("Status", table_header_style)],
        [Paragraph("<b>Overall Quality Score</b>", body_style), Paragraph(f"<b>{scores.get('overall_score', 0)} / 100</b>", body_style), Paragraph("Composite Index", body_style)],
        [Paragraph("Missing Data Score", body_style), Paragraph(f"{scores.get('missing_data_score', 0)} / 100", body_style), Paragraph("Completeness", body_style)],
        [Paragraph("Duplicate Record Score", body_style), Paragraph(f"{scores.get('duplicate_score', 0)} / 100", body_style), Paragraph("Uniqueness", body_style)],
        [Paragraph("Temporal Consistency Score", body_style), Paragraph(f"{scores.get('temporal_score', 0)} / 100", body_style), Paragraph("Chronology", body_style)],
        [Paragraph("Outlier & Plausibility Score", body_style), Paragraph(f"{scores.get('outlier_score', 0)} / 100", body_style), Paragraph("Measurement Validity", body_style)],
    ]

    t_scores = Table(score_data, colWidths=[200, 150, 190])
    t_scores.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0f172a')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
        ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor('#e0f2fe')),
    ]))
    story.append(t_scores)
    story.append(Spacer(1, 15))

    # Cohort Summary if available
    if cohort_summary:
        story.append(Paragraph("2. Cohort Parameters", heading2_style))
        story.append(Paragraph(f"<b>Query Description:</b> {cohort_summary.get('query', 'N/A')}", body_style))
        story.append(Paragraph(f"<b>Matched Patients:</b> {cohort_summary.get('matched_count', 0)} / {cohort_summary.get('total_patients', 0)}", body_style))
        story.append(Spacer(1, 15))

    # Issues & Clinical Impact Table
    story.append(Paragraph("3. Flagged Issues & Clinical Impact Analysis", heading2_style))
    story.append(Paragraph(
        f"Total Quality Issues Flagged: <b>{len(issues)}</b>. Each issue includes risk rating, "
        "clinical impact explanation, and recommended mitigation actions.",
        body_style
    ))
    story.append(Spacer(1, 8))

    issue_table_data = [
        [
            Paragraph("Table & Type", table_header_style),
            Paragraph("Risk Level", table_header_style),
            Paragraph("Clinical & Research Impact", table_header_style),
            Paragraph("Recommended Action", table_header_style)
        ]
    ]

    for iss in issues[:15]:  # Top 15 issues for PDF readability
        risk = iss.get("risk_level", "Medium")
        issue_table_data.append([
            Paragraph(f"<b>{iss.get('table', '')}</b><br/>{iss.get('type', '')}", body_style),
            Paragraph(f"<b>{risk}</b>", body_style),
            Paragraph(f"<b>Clinical:</b> {iss.get('clinical_impact', '')}<br/><b>Research:</b> {iss.get('research_impact', '')}", body_style),
            Paragraph(iss.get("recommended_action", ""), body_style)
        ])

    if not issues:
        issue_table_data.append([Paragraph("No issues flagged.", body_style), Paragraph("-", body_style), Paragraph("-", body_style), Paragraph("-", body_style)])

    t_issues = Table(issue_table_data, colWidths=[110, 65, 215, 150])
    t_issues.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0f172a')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
    ]))
    story.append(t_issues)
    story.append(Spacer(1, 15))

    # Recommendations & Safety Disclaimer
    story.append(Paragraph("4. Safety & Governance Statement", heading2_style))
    story.append(Paragraph(
        "<b>Notice:</b> This automated PDF audit report is a research prototype. It does not modify "
        "underlying hospital database CSV files. Flagged issues require human reviewer validation "
        "prior to cohort extraction or clinical trial model fitting.",
        body_style
    ))

    doc.build(story)
    return output_path
